### ISSUE TITLE
Add "roles" for site administrators and channels

### ISSUE THREAD

**Issue by omarroth** [omarroth/invidious#312]
For folks hosting their own instance of Invidious, it is desirable to customize the home page and disable various other aspects of the site. Some of the desired options include:
- [x] Hide watched videos or disable "top" page for smaller instances #294 
- [x] Disable creation of new users #293 
- [x] Change default home page #295 
- [x] Disable captcha #320

Although other options for administrators would also be helpful for managing instances. This issue would also include the ability to change the role of a user to administrator or channel owner, the latter of which would likely be done automatically. 

In #264, there was some mention of allowing channel owners to change comment settings under videos, and I can see that functionality being extended to be more useful. I'll probably add a list here as well for any functionality that is suggested.

This issue is to help track the functionality mentioned [here](https://github.com/omarroth/invidious/issues/294#issuecomment-455814716), and as a prerequisite for the above issues.

**Comment by tmiland** [comment]
Any progress on "Hide watched videos or disable "top" page for smaller instances"? 🙂

**Comment by omarroth** [comment]
Unfortunately not. I've been focusing on bug fixes before new features, so I haven't had much time to look at this. Consider this first on the list.

**Comment by tmiland** [comment]
> Unfortunately not. I've been focusing on bug fixes before new features, so I haven't had much time to look at this. Consider this first on the list.

Thank you, no worries. 👍

**Comment by Perflyst** [comment]
Just a side node, if you add your instance to the public instance list in the wiki, users come from alone and fill your "Top" with a lot of crazy stuff.

**Comment by omarroth** [comment]
Added with a39b158. You can make yourself an administrator by adding your user ID to the config like this:
```yaml
#...
domain: invidio.us
admins:
- YOUR_USER_ID
```

Which will show the following in `/preferences`:
![image](https://user-images.githubusercontent.com/14208607/53669428-aaa2a180-3c3c-11e9-8fe7-d4c482e21430.png)

Saving site preferences will write to `config.yml`. You can also edit the config directly. 

I'd like there to be a better way of designating a user admin. For assigning a user as owner of a channel, I'll plan on adding a `role` column to `users`, and refactoring this to work similarly.

For additional preferences I'd recommend opening a new issue. Since support for administrator preferences have been added I'm going to close this, and handle channel owners as a separate issue.
