### ISSUE TITLE
[meta] Comments rework

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#341]
The following changes have been requested (in no particular order) in the past:

- [ ] Sorting #101;
- [ ] Permalinks #340;
- [ ] Allow to load replies with JS disabled #204;
- [ ] Automatically show more comments when scrolling down #79; 
- [ ] Allow to hide commentsby default #94;
- [ ] High-res user avatars #184; 
- [ ] A possibility to add new comments and likes #300;
- [ ] ActivityPub integration #264;

**Comment by omarroth** [comment]
Thanks for organizing everything here. I've reordered everything from top to bottom in the order that they will likely be implemented.

**Comment by dimqua** [comment]
>Having a separate comments page would be great; not only for loading replies without JS, but also for being able to view pages of comments without JS.

**Comment by omarroth** [comment]
Added #409 to list of tracked issues.

**Comment by OrionRandD** [comment]
@omarroth  How do I comment videos on invidio? Haven't figured it out.
Could you make a video explaining it?
Anyways, thx for the app

**Comment by omarroth** [comment]
Currently it is not possible to comment on videos, see #300.

**Comment by OrionRandD** [comment]
@omarroth ok thx for replying...

**Comment by tomthumb876** [comment]
Exactly a year will have passed as of tomorrow on this, is there any update on where things stand? Beginning next month, Google will be forcing everyone onto the ghastly new layout, so invidio.us will be the only realistic YouTube viewing option for many people, myself included. With that in mind, it would be very reassuring to know that the highly necessary items on the above list of improvements have at least not been forgotten, and some sense of what the time scale might be for the implementation of at least the first few entries on the list. Thanks.

**Comment by SamantazFox** [comment]
bump
