### ISSUE TITLE
[Meta] Enhance and expand channel overview

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#483]
This is a meta issue for features which are available on YouTube if you are on a channel but missing on Invidious

- [ ] Profile image
- [ ] Profile banner

- [ ] Community (e.g. https://www.youtube.com/user/BBC/community)
- [ ] Channels, Featured channels (e.g. https://www.youtube.com/user/BBC/channels)
- [ ] About (e.g. https://www.youtube.com/user/BBC/about)

**Comment by omarroth** [comment]
Related: #152

**Comment by elypter** [comment]
channel search is also something very useful

**Comment by omarroth** [comment]
Channel search is supported using [`channel:UCID` syntax](https://invidio.us/search?q=channel%3AUC6nSFpj9HTCZ5t-N3Rm3-HA+mind+field). Although should be made more user-friendly with #179.

**Comment by omarroth** [comment]
Added banner and thumbnail with 0d0d3edeae1e632afc302e240b5ef7481c21b4b0.

Featured channels and information provided on the "About" page is already provided in the API, so adding it to the channel page should be fairly straight-forward.

**Comment by omarroth** [comment]
Added communities as `/api/v1/channels/comments/:ucid` with 196ee1aa8bb7e722fe32b77bc00c52b99d96b9ae. Similarly to the above, should be a mostly straight-forward addition for a "community" page now that support has been added to the API.

**Comment by omarroth** [comment]
Added community page with bcd239ac2b438ec721ffe35868371a9c81573f0a.

**Comment by elypter** [comment]
i get an error when opening this oage https://invidio.us/channel/UCLLibJTCy3sXjHLVaDimnpQ/community

**Comment by Perflyst** [comment]
@elypter this bug got fixed with af592ea8c15eeb985edecd875c66b05486bf7f89

I have added "Subscriptions" to the features list in the first post

**Comment by omarroth** [comment]
Added description with f71d5c429d4e3abc4e6a7eaf461fd46587316121.

**Comment by Perflyst** [comment]
I do not think we should mark "About" as done. There is also Details, Links and Stats available

**Comment by TheFrenchGhosty** [comment]
Still useful.

**Comment by SamantazFox** [comment]
still relevant
